### PR TITLE
initial design of PFT protocol

### PR DESCRIPTION
**Pull request by buchgr**
Hi guys!

This PR just contains the frame definitions. I didn't have enough time to write up all the semantics. Will do ASAP. It should be quite self explantory still, as we already discussed most of the protocol on Tuesday.

Please check it out and give me some feedback. I also created an issue #1 for implementing the framing types and the encoding / decoding.

### CODE REVIEW

**Comment by buchgr** [comment]
@bhatanku1 @RabbidDog @pulakchakraborty

**Comment by bhatanku1** [comment]
Hello Jacob,
The protocol looks better now. It is simpler than the first version. I did not understand the Checksum Packet though since we did not discuss it . But I guess when you write the description, it will be clear.

**Comment by buchgr** [comment]
@bhatanku1 

The checksum packet is not strictly required. The idea is that a client or server can verify if a partially downloaded version is correct. Not sure if we need that. I figured it might be a good idea, after restarting a partial download or upload. 

Note that for simplicity, the SHA1 hashes in the UPLOAD / DOWNLOAD frames are always the hashes of the whole file. Never of the partial download.

Makes sense?

**Comment by bhatanku1** [comment]
Yes, now I get it. Actually we had mentioned this is the protocol spec to check if the partial download/upload is correct or not. So makes sense to have this.

**Pull request closed without merging**
